io.write("Enter a noun: ")
NOUN = io.read()
io.write("Enter a verb: ")
VERB = io.read()
io.write("Enter an adjective: ")
ADJECTIVE = io.read()
io.write("Enter an adverb: ")
ADVERB = io.read()
print("Do you " .. VERB .. " your " .. ADJECTIVE .. " " .. NOUN .. " " .. ADVERB .. "? That's hilarious!")
